### ISSUE TITLE
单击开始会话时出现错误，提示不能为awtk加载驱动

### ISSUE THREAD

**Issue by likesubject** [zlgopen/awtk-ui-automation#1]
李工，您好！我按照你的文档内容进行操作，在最后一个步骤启动会话的时候提示不能为awtk加载驱动，我想问问这个是什么问题呢？谢谢！
![image](https://user-images.githubusercontent.com/15309266/95580401-dbc69300-0a69-11eb-9cc6-1e4f65b2f001.png)

**Comment by xianjimli** [comment]
https://github.com/zlgopen/awtk-ui-automation/blob/master/docs/how_to_install_appium_for_awtk.md

1.3 这个步骤做了没。

**Comment by likesubject** [comment]
![image](https://user-images.githubusercontent.com/15309266/95641819-23373880-0ad7-11eb-9b9b-62f0186db334.png)
wo'y我已经替换了之前的appium，按照1.3这个步骤来做的

**Comment by xianjimli** [comment]
我这里没有问题，在Windows, Linux和MacOS都试过。

**Comment by likesubject** [comment]
![image](https://user-images.githubusercontent.com/15309266/95644595-3c95b000-0aea-11eb-9487-f6cef4ed199b.png)
嗯嗯，经过检查后现在可以正常使用了，npm install 的时候没有用管理员权限启动git bash 导致WindowsApplicationDriver.msi 没有安装成功，导致不能使用。
