### ISSUE TITLE
按照《安装支持 AWTK 自动测试的 appium》一文打开appium失败

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-ui-automation#3]
![image](https://github.com/zlgopen/awtk-ui-automation/assets/54085641/e73214c3-48ae-47bb-a3c2-535772f7f43f)

**Comment by xianjimli** [comment]
这个项目不维护了，请用新的UI测试工具：https://github.com/zlgopen/awtk/blob/master/tools/ui_test/README.md
